//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("shopModel", "FK__product__categor__03317E3D", "category", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Shop.category), "product", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Shop.product), true)]
[assembly: EdmRelationshipAttribute("shopModel", "FK__product__company__0425A276", "company", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Shop.company), "product", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Shop.product), true)]
[assembly: EdmRelationshipAttribute("shopModel", "FK__config__product___0CBAE877", "product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Shop.product), "config", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Shop.config), true)]
[assembly: EdmRelationshipAttribute("shopModel", "FK__sold__config_id__164452B1", "config", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Shop.config), "sold", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Shop.sold), true)]
[assembly: EdmRelationshipAttribute("shopModel", "FK__stock__config_id__0F975522", "config", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Shop.config), "stock", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Shop.stock), true)]
[assembly: EdmRelationshipAttribute("shopModel", "FK__sold__invoice_no__15502E78", "sales", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Shop.sale), "sold", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Shop.sold), true)]

#endregion

namespace Shop
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class shopEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new shopEntities object using the connection string found in the 'shopEntities' section of the application configuration file.
        /// </summary>
        public shopEntities() : base("name=shopEntities", "shopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new shopEntities object.
        /// </summary>
        public shopEntities(string connectionString) : base(connectionString, "shopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new shopEntities object.
        /// </summary>
        public shopEntities(EntityConnection connection) : base(connection, "shopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<category> categories
        {
            get
            {
                if ((_categories == null))
                {
                    _categories = base.CreateObjectSet<category>("categories");
                }
                return _categories;
            }
        }
        private ObjectSet<category> _categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<company> companies
        {
            get
            {
                if ((_companies == null))
                {
                    _companies = base.CreateObjectSet<company>("companies");
                }
                return _companies;
            }
        }
        private ObjectSet<company> _companies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<config> configs
        {
            get
            {
                if ((_configs == null))
                {
                    _configs = base.CreateObjectSet<config>("configs");
                }
                return _configs;
            }
        }
        private ObjectSet<config> _configs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<product> products
        {
            get
            {
                if ((_products == null))
                {
                    _products = base.CreateObjectSet<product>("products");
                }
                return _products;
            }
        }
        private ObjectSet<product> _products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<registration> registrations
        {
            get
            {
                if ((_registrations == null))
                {
                    _registrations = base.CreateObjectSet<registration>("registrations");
                }
                return _registrations;
            }
        }
        private ObjectSet<registration> _registrations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sale> sales
        {
            get
            {
                if ((_sales == null))
                {
                    _sales = base.CreateObjectSet<sale>("sales");
                }
                return _sales;
            }
        }
        private ObjectSet<sale> _sales;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sold> solds
        {
            get
            {
                if ((_solds == null))
                {
                    _solds = base.CreateObjectSet<sold>("solds");
                }
                return _solds;
            }
        }
        private ObjectSet<sold> _solds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<stock> stocks
        {
            get
            {
                if ((_stocks == null))
                {
                    _stocks = base.CreateObjectSet<stock>("stocks");
                }
                return _stocks;
            }
        }
        private ObjectSet<stock> _stocks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocategories(category category)
        {
            base.AddObject("categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the companies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocompanies(company company)
        {
            base.AddObject("companies", company);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the configs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToconfigs(config config)
        {
            base.AddObject("configs", config);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproducts(product product)
        {
            base.AddObject("products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the registrations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToregistrations(registration registration)
        {
            base.AddObject("registrations", registration);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sales EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosales(sale sale)
        {
            base.AddObject("sales", sale);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the solds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosolds(sold sold)
        {
            base.AddObject("solds", sold);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the stocks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostocks(stock stock)
        {
            base.AddObject("stocks", stock);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="shopModel", Name="category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new category object.
        /// </summary>
        /// <param name="category_name">Initial value of the category_name property.</param>
        public static category Createcategory(global::System.String category_name)
        {
            category category = new category();
            category.category_name = category_name;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String category_name
        {
            get
            {
                return _category_name;
            }
            set
            {
                if (_category_name != value)
                {
                    Oncategory_nameChanging(value);
                    ReportPropertyChanging("category_name");
                    _category_name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("category_name");
                    Oncategory_nameChanged();
                }
            }
        }
        private global::System.String _category_name;
        partial void Oncategory_nameChanging(global::System.String value);
        partial void Oncategory_nameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("shopModel", "FK__product__categor__03317E3D", "product")]
        public EntityCollection<product> products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<product>("shopModel.FK__product__categor__03317E3D", "product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<product>("shopModel.FK__product__categor__03317E3D", "product", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="shopModel", Name="company")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class company : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new company object.
        /// </summary>
        /// <param name="company_name">Initial value of the company_name property.</param>
        public static company Createcompany(global::System.String company_name)
        {
            company company = new company();
            company.company_name = company_name;
            return company;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String company_name
        {
            get
            {
                return _company_name;
            }
            set
            {
                if (_company_name != value)
                {
                    Oncompany_nameChanging(value);
                    ReportPropertyChanging("company_name");
                    _company_name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("company_name");
                    Oncompany_nameChanged();
                }
            }
        }
        private global::System.String _company_name;
        partial void Oncompany_nameChanging(global::System.String value);
        partial void Oncompany_nameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("shopModel", "FK__product__company__0425A276", "product")]
        public EntityCollection<product> products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<product>("shopModel.FK__product__company__0425A276", "product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<product>("shopModel.FK__product__company__0425A276", "product", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="shopModel", Name="config")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class config : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new config object.
        /// </summary>
        /// <param name="config_id">Initial value of the config_id property.</param>
        /// <param name="product_name">Initial value of the product_name property.</param>
        /// <param name="price">Initial value of the price property.</param>
        public static config Createconfig(global::System.Int32 config_id, global::System.String product_name, global::System.Decimal price)
        {
            config config = new config();
            config.config_id = config_id;
            config.product_name = product_name;
            config.price = price;
            return config;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 config_id
        {
            get
            {
                return _config_id;
            }
            set
            {
                if (_config_id != value)
                {
                    Onconfig_idChanging(value);
                    ReportPropertyChanging("config_id");
                    _config_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("config_id");
                    Onconfig_idChanged();
                }
            }
        }
        private global::System.Int32 _config_id;
        partial void Onconfig_idChanging(global::System.Int32 value);
        partial void Onconfig_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String product_name
        {
            get
            {
                return _product_name;
            }
            set
            {
                Onproduct_nameChanging(value);
                ReportPropertyChanging("product_name");
                _product_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("product_name");
                Onproduct_nameChanged();
            }
        }
        private global::System.String _product_name;
        partial void Onproduct_nameChanging(global::System.String value);
        partial void Onproduct_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String features
        {
            get
            {
                return _features;
            }
            set
            {
                OnfeaturesChanging(value);
                ReportPropertyChanging("features");
                _features = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("features");
                OnfeaturesChanged();
            }
        }
        private global::System.String _features;
        partial void OnfeaturesChanging(global::System.String value);
        partial void OnfeaturesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Decimal _price;
        partial void OnpriceChanging(global::System.Decimal value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> sale_price
        {
            get
            {
                return _sale_price;
            }
            set
            {
                Onsale_priceChanging(value);
                ReportPropertyChanging("sale_price");
                _sale_price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sale_price");
                Onsale_priceChanged();
            }
        }
        private Nullable<global::System.Decimal> _sale_price;
        partial void Onsale_priceChanging(Nullable<global::System.Decimal> value);
        partial void Onsale_priceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("shopModel", "FK__config__product___0CBAE877", "product")]
        public product product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<product>("shopModel.FK__config__product___0CBAE877", "product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<product>("shopModel.FK__config__product___0CBAE877", "product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<product> productReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<product>("shopModel.FK__config__product___0CBAE877", "product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<product>("shopModel.FK__config__product___0CBAE877", "product", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("shopModel", "FK__sold__config_id__164452B1", "sold")]
        public EntityCollection<sold> solds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<sold>("shopModel.FK__sold__config_id__164452B1", "sold");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<sold>("shopModel.FK__sold__config_id__164452B1", "sold", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("shopModel", "FK__stock__config_id__0F975522", "stock")]
        public EntityCollection<stock> stocks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<stock>("shopModel.FK__stock__config_id__0F975522", "stock");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<stock>("shopModel.FK__stock__config_id__0F975522", "stock", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="shopModel", Name="product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new product object.
        /// </summary>
        /// <param name="product_name">Initial value of the product_name property.</param>
        /// <param name="category_name">Initial value of the category_name property.</param>
        /// <param name="company_name">Initial value of the company_name property.</param>
        public static product Createproduct(global::System.String product_name, global::System.String category_name, global::System.String company_name)
        {
            product product = new product();
            product.product_name = product_name;
            product.category_name = category_name;
            product.company_name = company_name;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String product_name
        {
            get
            {
                return _product_name;
            }
            set
            {
                if (_product_name != value)
                {
                    Onproduct_nameChanging(value);
                    ReportPropertyChanging("product_name");
                    _product_name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("product_name");
                    Onproduct_nameChanged();
                }
            }
        }
        private global::System.String _product_name;
        partial void Onproduct_nameChanging(global::System.String value);
        partial void Onproduct_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String category_name
        {
            get
            {
                return _category_name;
            }
            set
            {
                Oncategory_nameChanging(value);
                ReportPropertyChanging("category_name");
                _category_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("category_name");
                Oncategory_nameChanged();
            }
        }
        private global::System.String _category_name;
        partial void Oncategory_nameChanging(global::System.String value);
        partial void Oncategory_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String company_name
        {
            get
            {
                return _company_name;
            }
            set
            {
                Oncompany_nameChanging(value);
                ReportPropertyChanging("company_name");
                _company_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("company_name");
                Oncompany_nameChanged();
            }
        }
        private global::System.String _company_name;
        partial void Oncompany_nameChanging(global::System.String value);
        partial void Oncompany_nameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("shopModel", "FK__product__categor__03317E3D", "category")]
        public category category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<category>("shopModel.FK__product__categor__03317E3D", "category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<category>("shopModel.FK__product__categor__03317E3D", "category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<category> categoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<category>("shopModel.FK__product__categor__03317E3D", "category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<category>("shopModel.FK__product__categor__03317E3D", "category", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("shopModel", "FK__product__company__0425A276", "company")]
        public company company
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<company>("shopModel.FK__product__company__0425A276", "company").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<company>("shopModel.FK__product__company__0425A276", "company").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<company> companyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<company>("shopModel.FK__product__company__0425A276", "company");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<company>("shopModel.FK__product__company__0425A276", "company", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("shopModel", "FK__config__product___0CBAE877", "config")]
        public EntityCollection<config> configs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<config>("shopModel.FK__config__product___0CBAE877", "config");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<config>("shopModel.FK__config__product___0CBAE877", "config", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="shopModel", Name="registration")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class registration : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new registration object.
        /// </summary>
        /// <param name="c_name">Initial value of the C_name property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="c_password">Initial value of the C_password property.</param>
        /// <param name="c_role">Initial value of the C_role property.</param>
        public static registration Createregistration(global::System.String c_name, global::System.String username, global::System.String c_password, global::System.String c_role)
        {
            registration registration = new registration();
            registration.C_name = c_name;
            registration.username = username;
            registration.C_password = c_password;
            registration.C_role = c_role;
            return registration;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String C_name
        {
            get
            {
                return _C_name;
            }
            set
            {
                OnC_nameChanging(value);
                ReportPropertyChanging("C_name");
                _C_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("C_name");
                OnC_nameChanged();
            }
        }
        private global::System.String _C_name;
        partial void OnC_nameChanging(global::System.String value);
        partial void OnC_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                if (_username != value)
                {
                    OnusernameChanging(value);
                    ReportPropertyChanging("username");
                    _username = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("username");
                    OnusernameChanged();
                }
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String C_password
        {
            get
            {
                return _C_password;
            }
            set
            {
                OnC_passwordChanging(value);
                ReportPropertyChanging("C_password");
                _C_password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("C_password");
                OnC_passwordChanged();
            }
        }
        private global::System.String _C_password;
        partial void OnC_passwordChanging(global::System.String value);
        partial void OnC_passwordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contactno
        {
            get
            {
                return _contactno;
            }
            set
            {
                OncontactnoChanging(value);
                ReportPropertyChanging("contactno");
                _contactno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contactno");
                OncontactnoChanged();
            }
        }
        private global::System.String _contactno;
        partial void OncontactnoChanging(global::System.String value);
        partial void OncontactnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String joiningdate
        {
            get
            {
                return _joiningdate;
            }
            set
            {
                OnjoiningdateChanging(value);
                ReportPropertyChanging("joiningdate");
                _joiningdate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("joiningdate");
                OnjoiningdateChanged();
            }
        }
        private global::System.String _joiningdate;
        partial void OnjoiningdateChanging(global::System.String value);
        partial void OnjoiningdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String C_role
        {
            get
            {
                return _C_role;
            }
            set
            {
                OnC_roleChanging(value);
                ReportPropertyChanging("C_role");
                _C_role = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("C_role");
                OnC_roleChanged();
            }
        }
        private global::System.String _C_role;
        partial void OnC_roleChanging(global::System.String value);
        partial void OnC_roleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="shopModel", Name="sale")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sale : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sale object.
        /// </summary>
        /// <param name="invoice_no">Initial value of the invoice_no property.</param>
        public static sale Createsale(global::System.String invoice_no)
        {
            sale sale = new sale();
            sale.invoice_no = invoice_no;
            return sale;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String invoice_no
        {
            get
            {
                return _invoice_no;
            }
            set
            {
                if (_invoice_no != value)
                {
                    Oninvoice_noChanging(value);
                    ReportPropertyChanging("invoice_no");
                    _invoice_no = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("invoice_no");
                    Oninvoice_noChanged();
                }
            }
        }
        private global::System.String _invoice_no;
        partial void Oninvoice_noChanging(global::System.String value);
        partial void Oninvoice_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String invoice_date
        {
            get
            {
                return _invoice_date;
            }
            set
            {
                Oninvoice_dateChanging(value);
                ReportPropertyChanging("invoice_date");
                _invoice_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("invoice_date");
                Oninvoice_dateChanged();
            }
        }
        private global::System.String _invoice_date;
        partial void Oninvoice_dateChanging(global::System.String value);
        partial void Oninvoice_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String customer_name
        {
            get
            {
                return _customer_name;
            }
            set
            {
                Oncustomer_nameChanging(value);
                ReportPropertyChanging("customer_name");
                _customer_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("customer_name");
                Oncustomer_nameChanged();
            }
        }
        private global::System.String _customer_name;
        partial void Oncustomer_nameChanging(global::System.String value);
        partial void Oncustomer_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> total
        {
            get
            {
                return _total;
            }
            set
            {
                OntotalChanging(value);
                ReportPropertyChanging("total");
                _total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total");
                OntotalChanged();
            }
        }
        private Nullable<global::System.Decimal> _total;
        partial void OntotalChanging(Nullable<global::System.Decimal> value);
        partial void OntotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> discount
        {
            get
            {
                return _discount;
            }
            set
            {
                OndiscountChanging(value);
                ReportPropertyChanging("discount");
                _discount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("discount");
                OndiscountChanged();
            }
        }
        private Nullable<global::System.Decimal> _discount;
        partial void OndiscountChanging(Nullable<global::System.Decimal> value);
        partial void OndiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> received
        {
            get
            {
                return _received;
            }
            set
            {
                OnreceivedChanging(value);
                ReportPropertyChanging("received");
                _received = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("received");
                OnreceivedChanged();
            }
        }
        private Nullable<global::System.Decimal> _received;
        partial void OnreceivedChanging(Nullable<global::System.Decimal> value);
        partial void OnreceivedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String remarks
        {
            get
            {
                return _remarks;
            }
            set
            {
                OnremarksChanging(value);
                ReportPropertyChanging("remarks");
                _remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("remarks");
                OnremarksChanged();
            }
        }
        private global::System.String _remarks;
        partial void OnremarksChanging(global::System.String value);
        partial void OnremarksChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("shopModel", "FK__sold__invoice_no__15502E78", "sold")]
        public EntityCollection<sold> solds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<sold>("shopModel.FK__sold__invoice_no__15502E78", "sold");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<sold>("shopModel.FK__sold__invoice_no__15502E78", "sold", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="shopModel", Name="sold")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sold : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sold object.
        /// </summary>
        /// <param name="sold_id">Initial value of the sold_id property.</param>
        /// <param name="invoice_no">Initial value of the invoice_no property.</param>
        /// <param name="config_id">Initial value of the config_id property.</param>
        /// <param name="quantity">Initial value of the quantity property.</param>
        /// <param name="price">Initial value of the price property.</param>
        /// <param name="total">Initial value of the total property.</param>
        public static sold Createsold(global::System.Int32 sold_id, global::System.String invoice_no, global::System.Int32 config_id, global::System.Decimal quantity, global::System.Decimal price, global::System.Decimal total)
        {
            sold sold = new sold();
            sold.sold_id = sold_id;
            sold.invoice_no = invoice_no;
            sold.config_id = config_id;
            sold.quantity = quantity;
            sold.price = price;
            sold.total = total;
            return sold;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sold_id
        {
            get
            {
                return _sold_id;
            }
            set
            {
                if (_sold_id != value)
                {
                    Onsold_idChanging(value);
                    ReportPropertyChanging("sold_id");
                    _sold_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sold_id");
                    Onsold_idChanged();
                }
            }
        }
        private global::System.Int32 _sold_id;
        partial void Onsold_idChanging(global::System.Int32 value);
        partial void Onsold_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String invoice_no
        {
            get
            {
                return _invoice_no;
            }
            set
            {
                Oninvoice_noChanging(value);
                ReportPropertyChanging("invoice_no");
                _invoice_no = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("invoice_no");
                Oninvoice_noChanged();
            }
        }
        private global::System.String _invoice_no;
        partial void Oninvoice_noChanging(global::System.String value);
        partial void Oninvoice_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 config_id
        {
            get
            {
                return _config_id;
            }
            set
            {
                Onconfig_idChanging(value);
                ReportPropertyChanging("config_id");
                _config_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("config_id");
                Onconfig_idChanged();
            }
        }
        private global::System.Int32 _config_id;
        partial void Onconfig_idChanging(global::System.Int32 value);
        partial void Onconfig_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal quantity
        {
            get
            {
                return _quantity;
            }
            set
            {
                OnquantityChanging(value);
                ReportPropertyChanging("quantity");
                _quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quantity");
                OnquantityChanged();
            }
        }
        private global::System.Decimal _quantity;
        partial void OnquantityChanging(global::System.Decimal value);
        partial void OnquantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Decimal _price;
        partial void OnpriceChanging(global::System.Decimal value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal total
        {
            get
            {
                return _total;
            }
            set
            {
                OntotalChanging(value);
                ReportPropertyChanging("total");
                _total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total");
                OntotalChanged();
            }
        }
        private global::System.Decimal _total;
        partial void OntotalChanging(global::System.Decimal value);
        partial void OntotalChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("shopModel", "FK__sold__config_id__164452B1", "config")]
        public config config
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<config>("shopModel.FK__sold__config_id__164452B1", "config").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<config>("shopModel.FK__sold__config_id__164452B1", "config").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<config> configReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<config>("shopModel.FK__sold__config_id__164452B1", "config");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<config>("shopModel.FK__sold__config_id__164452B1", "config", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("shopModel", "FK__sold__invoice_no__15502E78", "sales")]
        public sale sale
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sale>("shopModel.FK__sold__invoice_no__15502E78", "sales").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sale>("shopModel.FK__sold__invoice_no__15502E78", "sales").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<sale> saleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sale>("shopModel.FK__sold__invoice_no__15502E78", "sales");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<sale>("shopModel.FK__sold__invoice_no__15502E78", "sales", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="shopModel", Name="stock")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class stock : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new stock object.
        /// </summary>
        /// <param name="stock_id">Initial value of the stock_id property.</param>
        /// <param name="config_id">Initial value of the config_id property.</param>
        /// <param name="quantity">Initial value of the quantity property.</param>
        /// <param name="total_price">Initial value of the total_price property.</param>
        public static stock Createstock(global::System.Int32 stock_id, global::System.Int32 config_id, global::System.Decimal quantity, global::System.Decimal total_price)
        {
            stock stock = new stock();
            stock.stock_id = stock_id;
            stock.config_id = config_id;
            stock.quantity = quantity;
            stock.total_price = total_price;
            return stock;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stock_id
        {
            get
            {
                return _stock_id;
            }
            set
            {
                if (_stock_id != value)
                {
                    Onstock_idChanging(value);
                    ReportPropertyChanging("stock_id");
                    _stock_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("stock_id");
                    Onstock_idChanged();
                }
            }
        }
        private global::System.Int32 _stock_id;
        partial void Onstock_idChanging(global::System.Int32 value);
        partial void Onstock_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 config_id
        {
            get
            {
                return _config_id;
            }
            set
            {
                Onconfig_idChanging(value);
                ReportPropertyChanging("config_id");
                _config_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("config_id");
                Onconfig_idChanged();
            }
        }
        private global::System.Int32 _config_id;
        partial void Onconfig_idChanging(global::System.Int32 value);
        partial void Onconfig_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal quantity
        {
            get
            {
                return _quantity;
            }
            set
            {
                OnquantityChanging(value);
                ReportPropertyChanging("quantity");
                _quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quantity");
                OnquantityChanged();
            }
        }
        private global::System.Decimal _quantity;
        partial void OnquantityChanging(global::System.Decimal value);
        partial void OnquantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal total_price
        {
            get
            {
                return _total_price;
            }
            set
            {
                Ontotal_priceChanging(value);
                ReportPropertyChanging("total_price");
                _total_price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total_price");
                Ontotal_priceChanged();
            }
        }
        private global::System.Decimal _total_price;
        partial void Ontotal_priceChanging(global::System.Decimal value);
        partial void Ontotal_priceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stock_date
        {
            get
            {
                return _stock_date;
            }
            set
            {
                Onstock_dateChanging(value);
                ReportPropertyChanging("stock_date");
                _stock_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stock_date");
                Onstock_dateChanged();
            }
        }
        private global::System.String _stock_date;
        partial void Onstock_dateChanging(global::System.String value);
        partial void Onstock_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("shopModel", "FK__stock__config_id__0F975522", "config")]
        public config config
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<config>("shopModel.FK__stock__config_id__0F975522", "config").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<config>("shopModel.FK__stock__config_id__0F975522", "config").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<config> configReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<config>("shopModel.FK__stock__config_id__0F975522", "config");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<config>("shopModel.FK__stock__config_id__0F975522", "config", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="shopModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }

    #endregion
    
}
